/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddRocketDialog: typeof import('./src/components/AddRocketDialog.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RequestState: typeof import('./src/components/RequestState.vue')['default']
    RocketCard: typeof import('./src/components/RocketCard.vue')['default']
    RocketCardSkeleton: typeof import('./src/components/RocketCardSkeleton.vue')['default']
    RocketFilters: typeof import('./src/components/RocketFilters.vue')['default']
    RocketImage: typeof import('./src/components/RocketImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
